proteinToRna = { 'A' : 4,
                 'C' : 2,
                 'D' : 2,
                 'E' : 2,
                 'F' : 2,
                 'G' : 4,
                 'H' : 2,
                 'I' : 3,
                 'L' : 6,
                 'M' : 1,
                 'N' : 2,
                 'P' : 4,
                 'R' : 6,
                 'S' : 6,
                 'T' : 4,
                 'K' : 2,
                 'V' : 4,
                 'W' : 1,
                 'Q' : 2,
                 'Y' : 2
}

modu = 1000000

def noOfRNA(proteinlist):
    rnaCombination = 1
    for x in range(0,len(proteinlist)):
        number = proteinToRna.get(proteinlist[x])
        rnaCombination = (rnaCombination * number)%modu

    rnaCombination = (rnaCombination * 3)%modu
    return rnaCombination

print(noOfRNA(("MYKYRGHQTICRCNMNCSIQDKNHNPITPCRRAMSPVFNVGEITTSPPSVDFTGCAHQQGEYMTLEQIVMFNGLYFCHNYWGLTISHFFGELQFDFAMWE"
               "DACQRTDWLDKRNPTKSIADNHNMSARKLWKVYNHFLMPINSDILVYTFQDLINTRKTHMYPFNSNKDFTKYNIRWEPSTCTCEKPLSNGNSSDFDLPAWFV"
               "FMCSVYEMFCQKWCCQKCVTYAKTDFEDCLWYSEAWPLVWRVFQNVQIEVTAEMPQPDQSNELRELVFYMGQYHCLHCKMLCHCNFQNWAIYFLIFMMCTYMQ"
               "GVNGSWTPQVFSMCSLDFALSMDKISSPASKMHNRFATMVHYYLDSCCRMEATCDCLSTMLYKTDEADFTIQWNFTLWEPGWCRYKDVADRHTPHQFANGHPG"
               "RGSNTWATRSYAFDKDCPIDGAFRETRLAYGWKKWECNDFLNLERQNTKTNRKMALGETELHLPHQYTSMTRQVADVWTCPNPKSMPIMDGLPDSFERESCYL"
               "EQLWNCCTNHVYPEKTCDAEFINKYRWSKSYQPLVIFPLWNELHYGQHPVHVLGTHPIWLHCNQDCKQQLFYALQMGDRQDFGTKGQFMKSWCDVGAVSGILD"
               "KMEFERANCLGTMGKYQICWKERNHYHTHTIWEKLIRYNTLAFEDKRLRFYKMSSEMCMWEDPMEWISYVPVNKFMQDLTMHRYCQRSLKKSALAIDRVDERR"
               "NVERYMEKCTKMKVVVHQDTHRALWPNWYSMDRKFILQMAIWKWVVLYDFMRIPWEMWWGCPNHKLCTFMAFYWHFQDQPARFTRSNPSMGQMTTRWPLPLII"
               "YYFNAQTAAFDWNNQWIVTMDQTAAEFARACCQLNLNHPFGHHSHEHPAYTRVWLQGHFCSMIIYLRGSRRMAMQEHHQFDYGNVDHGVKNGKAAVTNTTYCF"
               "LTPEIMCQLEDWEKGAVSHHAYKGRIITCSTVKTMFHEMMIKYGSGTEENYQLSDLYVYDQWPMWKGEHMEEYTKTI")))